# Generated by Django 4.0.6 on 2022-08-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_image/default.png', null=True, upload_to='profile_image/'),
        ),
    ]
