# Generated by Django 4.0.6 on 2022-08-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_favorito_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
        migrations.AddField(
            model_name='user',
            name='favs',
            field=models.ManyToManyField(to='products.producto'),
        ),
    ]
