# Generated by Django 4.0.6 on 2022-08-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_producto_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('P', 'Película'), ('S', 'Serie'), ('C', 'Corto')], max_length=1)),
                ('score', models.FloatField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('image_url', models.URLField(default='https://image.shutterstock.com/image-vector/photo-album-picture-collection-line-260nw-256926565.jpg')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='favs',
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default='admin@admin.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fav',
            field=models.ManyToManyField(to='products.contenido'),
        ),
    ]
