# Generated by Django 4.0.6 on 2022-08-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='image_url',
            field=models.URLField(default='https://nayemdevs.com/wp-content/uploads/2020/03/default-product-image.png'),
        ),
    ]
