# Generated by Django 4.0.6 on 2022-08-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_producto_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image_url',
            field=models.URLField(default='https://image.shutterstock.com/image-vector/photo-album-picture-collection-line-260nw-256926565.jpg'),
        ),
    ]
