# Generated by Django 4.0.6 on 2022-08-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_reseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseña',
            name='category',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='description',
        ),
    ]
