# Generated by Django 4.0.6 on 2022-08-09 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_reseña_category_remove_reseña_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseña',
            name='film',
        ),
        migrations.AddField(
            model_name='reseña',
            name='film',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.contenido'),
            preserve_default=False,
        ),
    ]
