# Generated by Django 4.0.6 on 2022-08-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_platforms_delete_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platforms',
            new_name='Platform',
        ),
    ]
