# Generated by Django 4.0.6 on 2022-08-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_platforms_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
