# Generated by Django 4.0.6 on 2022-09-12 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0014_alter_platform_name_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='author',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
